import{useEffect,useMemo,useRef,useState}from'react';import{personas}from'./personas';import{missions}from'./missions';import{BrowserSpeechService}from'./services/speech';import{getReply}from'./services/llm';import{applyEvaluation,earnedBadges}from'./scoring';import{useProgress}from'./hooks/useProgress';import type{GameStats,Message,Mission,Persona}from'./types';
type Screen='home'|'personas'|'missions'|'game'|'result';const blank:GameStats={score:0,greeting:false,questions:0,reactions:0,empathy:0,silenceBreaks:0,elapsed:0};
export default function App(){const[screen,setScreen]=useState<Screen>('home');const[persona,setPersona]=useState<Persona>();const[mission,setMission]=useState<Mission>();const[msgs,setMsgs]=useState<Message[]>([]);const[stats,setStats]=useState(blank);const[state,setState]=useState<'idle'|'listening'|'thinking'|'speaking'>('idle');const[notice,setNotice]=useState('');const[error,setError]=useState('');const speech=useMemo(()=>new BrowserSpeechService(),[]);const startAt=useRef(0);const{progress,save}=useProgress();
useEffect(()=>()=>speech.stop(),[speech]);useEffect(()=>{if(screen!=='game')return;const id=setInterval(()=>setStats(s=>({...s,elapsed:Math.floor((Date.now()-startAt.current)/1000)})),1000);return()=>clearInterval(id)},[screen]);
const begin=(m:Mission)=>{setMission(m);setMsgs([]);setStats(blank);setError('');startAt.current=Date.now();setScreen('game')};
const say=async()=>{if(!persona||state!=='idle')return;setError('');setState('listening');try{const text=await speech.listen();const student:Message={id:crypto.randomUUID(),role:'student',text};const next=[...msgs,student];setMsgs(next);setState('thinking');const waiting=msgs.at(-1)?.role==='elder'&&/^(그래|그렇구먼|허허)[~.]*$/.test(msgs.at(-1)?.text??'');const ai=await getReply(persona,next,waiting);const elder:Message={id:crypto.randomUUID(),role:'elder',text:ai.reply};setMsgs([...next,elder]);setStats(s=>{const n=applyEvaluation(s,ai.evaluation);const gained=n.score-s.score;if(gained){setNotice(`✨ 잘했어요! +${gained}`);setTimeout(()=>setNotice(''),1800)}return n});setState('speaking');await speech.speak(ai.reply)}catch(e){setError(e instanceof Error?e.message:'다시 시도해 주세요.')}finally{setState('idle')}};
const finish=()=>{if(!persona||!mission)return;speech.stop();const final={...stats,elapsed:Math.floor((Date.now()-startAt.current)/1000)};setStats(final);const badges=earnedBadges(final,mission.duration);save({practiceCount:progress.practiceCount+1,highScore:Math.max(progress.highScore,final.score),badges:[...new Set([...progress.badges,...badges])],completedPersonas:[...new Set([...progress.completedPersonas,persona.id])],completedMissions:[...new Set([...progress.completedMissions,mission.id])]});setScreen('result')};
if(screen==='home')return <Shell><main className="hero"><div className="logo">💛</div><span className="eyebrow">마음톡 · 아웃리치 대화 연습</span><h1>어르신과 대화할<br/>준비가 되었나요?</h1><p>정답은 없어요. 먼저 한마디 건네는 용기면 충분해요!</p><button className="primary" onClick={()=>setScreen('personas')}>연습 시작 <b>→</b></button><div className="mini-stats"><span>🎮 연습 {progress.practiceCount}회</span><span>⭐ 최고 {progress.highScore}점</span></div></main></Shell>;
if(screen==='personas')return <Shell title="누구를 만나볼까요?" back={()=>setScreen('home')}><p className="lead">카드를 눌러 대화 상대를 골라보세요.</p><div className="cards">{personas.map(p=><button className="person-card" key={p.id} onClick={()=>{setPersona(p);setScreen('missions')}}><span className="avatar">{p.emoji}</span><span><small className={p.difficulty==='쉬움'?'easy':'normal'}>{p.difficulty}</small><h2>{p.name}</h2><b>{p.tagline}</b><p>{p.personality}</p><i>{p.interests.map(x=>`#${x}`).join(' ')}</i></span><strong>›</strong></button>)}</div></Shell>;
if(screen==='missions')return <Shell title={`${persona?.name}과 무엇을 연습할까요?`} back={()=>setScreen('personas')}><p className="lead">오늘 도전할 미션 하나를 골라요.</p><div className="cards">{missions.map(m=><button className="mission-card" key={m.id} onClick={()=>begin(m)}><span>LEVEL {m.level}</span><div><h2>{m.title}</h2><p>{m.description}</p><small>⏱ {Math.ceil(m.duration/60)}분 · 질문 {m.targetQuestions}번</small></div><strong>›</strong></button>)}</div></Shell>;
if(screen==='game')return <div className="game"><header><button onClick={finish}>×</button><div><small>오늘의 미션</small><b>{mission?.title}</b></div><span>⭐ {stats.score}</span></header><section className="mission-strip"><span className={stats.greeting?'done':''}>인사 {stats.greeting?'✓':''}</span><span className={stats.questions>=(mission?.targetQuestions??0)?'done':''}>질문 {stats.questions}/{mission?.targetQuestions}</span><span className={stats.reactions>=(mission?.targetReactions??0)?'done':''}>리액션 {stats.reactions}/{mission?.targetReactions}</span></section><main className="voice"><div className={`voice-orb ${state}`}><span>{persona?.emoji}</span></div><h1>{persona?.name}</h1><p>{state==='listening'?'듣고 있어요...':state==='thinking'?'잠깐 생각하고 있어요...':state==='speaking'?'이야기하고 있어요':'버튼을 누르고 이야기해요'}</p>{notice&&<div className="toast">{notice}</div>}{error&&<div className="error">{error}</div>}<div className="transcript">{msgs.length===0?<p className="hint">먼저 “안녕하세요!” 하고 인사해 볼까요?</p>:msgs.map(m=><div className={m.role} key={m.id}><b>{m.role==='elder'?persona?.name:'나'}</b><p>{m.text}</p></div>)}</div></main><footer><button className={`mic ${state}`} onClick={say} disabled={state!=='idle'}>🎤 <span>{state==='idle'?'말하기':'대화 중'}</span></button><button className="finish" onClick={finish}>대화 마치기</button></footer></div>;
const badges=mission?earnedBadges(stats,mission.duration):[];return <Shell><main className="result"><div className="confetti">🎉</div><span className="eyebrow">대화 완료!</span><h1>용기 내어 이야기했어요</h1><div className="score"><small>오늘의 점수</small><strong>{stats.score}</strong><span>점</span></div><section><h2>획득 배지</h2><div className="badges">{badges.length?badges.map(b=><span key={b}>{b}</span>):<p>다음 도전에서 첫 배지를 만나봐요!</p>}</div></section><section className="feedback"><h2>오늘 잘한 점</h2>{stats.greeting&&<p>😊 먼저 밝게 인사했어요.</p>}<p>💬 질문을 {stats.questions}번 하며 대화를 이어갔어요.</p>{stats.empathy>0&&<p>❤️ 이야기에 따뜻하게 공감했어요.</p>}<h2>다음에는 이렇게!</h2><p>“저도 좋아해요!” 뒤에 “언제부터 좋아하셨어요?”처럼 질문을 하나 더 해보세요.</p></section><button className="primary" onClick={()=>mission&&begin(mission)}>같은 미션 다시 도전</button><button className="secondary" onClick={()=>setScreen('personas')}>다른 어르신 만나기</button></main></Shell>}
function Shell({children,title,back}:{children:React.ReactNode;title?:string;back?:()=>void}){return <div className="shell">{title&&<header className="top"><button onClick={back}>←</button><h1>{title}</h1></header>}{children}</div>}
